# -*- coding: utf-8 -*-
"""Tutorial-4 CN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tqp23M1VfG_SzXzQSxtXM2Tqt8VfgbDN
"""

pip install pingouin networkx numpy pandas seaborn matplotlib

import numpy as np
import pandas as pd
import networkx as nx
import pingouin as pg
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/dataFile.csv')
data = pd.DataFrame(df)
cols = data.columns

for col in cols:
  plt.figure(figsize=(10, 4))
  plt.plot(df.index, df[col], label={col})
  plt.title(f"Time series plot of {col}")
  plt.legend()
  plt.ylabel('Value')
  plt.grid(True)
  plt.tight_layout

# plotting the correlation heatmap
corr_mat = data.corr()

plt.figure(figsize=(6,6))
sns.heatmap(corr_mat, annot=True, cmap='coolwarm', square=True)
plt.title('Correlation Heatmap')
plt.show()

# calculating pairwise correlation
rho_ab = pg.partial_corr(data, ['Stock A', 'Stock B'], covar=['Supplier Co.', 'Sector Index', 'Stock C'])
rho_ac = pg.partial_corr(data, ['Stock A', 'Stock C'], covar=['Supplier Co.', 'Sector Index', 'Stock C'])
rho_asi = pg.partial_corr(data, ['Stock A', 'Sector Index'], covar=['Supplier Co.', 'Sector Index', 'Stock C'])
rho_asco = pg.partial_corr(data, ['Stock A', 'Supplier Co.'], covar=['Supplier Co.', 'Sector Index', 'Stock C'])
print(rho_ab)
print(rho_ac)
print(rho_asi)
print(rho_asco)

"""*`The above process can become a bit cumbersome and therefore we will use the pcorr() method in the pingouin library which calculates partial correlation between every two variables by keeping the others constants.`*"""

partial_corr_mat = data.pcorr()

plt.figure(figsize=(6,6))
sns.heatmap(partial_corr_mat, annot=True, cmap='coolwarm', square=True)
plt.title('Correlation Heatmap')
plt.show()

"""Building and drawing the network using networkx libraries."""

pc_threshold = 0.1

G = nx.Graph()
G.add_nodes_from(cols)

for i in range(len(cols)):
  for j in range(i+1, len(cols)):
    node_a = cols[i]
    node_b = cols[j]
    pc_value = partial_corr_mat.loc[node_a, node_b]

    if( abs(pc_value >= pc_threshold)):
      G.add_edge(node_a, node_b, weight=pc_value)
print(f"no. of nodes in the graph = {G.number_of_nodes()} and no. of edges in the graph = {G.number_of_edges()}")

plt.figure(figsize=(6,6))
pos = nx.kamada_kawai_layout(G)
nx.draw_networkx_nodes(G, pos, node_size=1000, node_color='gold')
nx.draw_networkx_edges(G, pos, edge_color='grey', width=1)
nx.draw_networkx_labels(G, pos, font_size=6, font_color='black', font_weight='bold')
plt.title("Partial Correlation Network(Threshold |r| >= 0.1)", fontsize=11)
plt.axis('off')
